### ISSUE TITLE
Проверить ДЗ (задачка по недвижимости)

### ISSUE THREAD

**Issue by dilyarakhabibullina** [dilyarakhabibullina/houses#1]

**Comment by coursar** [comment]
А где сам сервис поиска-то?

Вижу только класс, который описывает дом.

**Comment by dilyarakhabibullina** [comment]
Добрый день! У меня все в Main. Подскажите пожалуйста, как сделать List в отдельном сервисе, а не в Main? Нужно упаковать его в отдельный метод? Тогда что этот метод должен возвращать?

**Comment by coursar** [comment]
См. пример с лекций, мы же делали такое

**Comment by dilyarakhabibullina** [comment]
Вынесла добавление и поиск в отдельный сервис, посмотрите пож-та
